// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.23.4
// source: common.proto

package carserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Invalid int32

const (
	Invalid_INVALID Invalid = 0
)

// Enum value maps for Invalid.
var (
	Invalid_name = map[int32]string{
		0: "INVALID",
	}
	Invalid_value = map[string]int32{
		"INVALID": 0,
	}
)

func (x Invalid) Enum() *Invalid {
	p := new(Invalid)
	*p = x
	return p
}

func (x Invalid) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Invalid) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Invalid) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Invalid) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Invalid.Descriptor instead.
func (Invalid) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type MediaPlaybackStatus int32

const (
	MediaPlaybackStatus_Stopped MediaPlaybackStatus = 0
	MediaPlaybackStatus_Playing MediaPlaybackStatus = 1
	MediaPlaybackStatus_Paused  MediaPlaybackStatus = 2
)

// Enum value maps for MediaPlaybackStatus.
var (
	MediaPlaybackStatus_name = map[int32]string{
		0: "Stopped",
		1: "Playing",
		2: "Paused",
	}
	MediaPlaybackStatus_value = map[string]int32{
		"Stopped": 0,
		"Playing": 1,
		"Paused":  2,
	}
)

func (x MediaPlaybackStatus) Enum() *MediaPlaybackStatus {
	p := new(MediaPlaybackStatus)
	*p = x
	return p
}

func (x MediaPlaybackStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaPlaybackStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (MediaPlaybackStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x MediaPlaybackStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaPlaybackStatus.Descriptor instead.
func (MediaPlaybackStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type StwHeatLevel int32

const (
	StwHeatLevel_StwHeatLevel_Unknown StwHeatLevel = 0
	StwHeatLevel_StwHeatLevel_Off     StwHeatLevel = 1
	StwHeatLevel_StwHeatLevel_Low     StwHeatLevel = 2
	StwHeatLevel_StwHeatLevel_High    StwHeatLevel = 3
)

// Enum value maps for StwHeatLevel.
var (
	StwHeatLevel_name = map[int32]string{
		0: "StwHeatLevel_Unknown",
		1: "StwHeatLevel_Off",
		2: "StwHeatLevel_Low",
		3: "StwHeatLevel_High",
	}
	StwHeatLevel_value = map[string]int32{
		"StwHeatLevel_Unknown": 0,
		"StwHeatLevel_Off":     1,
		"StwHeatLevel_Low":     2,
		"StwHeatLevel_High":    3,
	}
)

func (x StwHeatLevel) Enum() *StwHeatLevel {
	p := new(StwHeatLevel)
	*p = x
	return p
}

func (x StwHeatLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StwHeatLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (StwHeatLevel) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x StwHeatLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StwHeatLevel.Descriptor instead.
func (StwHeatLevel) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type LatLong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float32                `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatLong) Reset() {
	*x = LatLong{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatLong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatLong) ProtoMessage() {}

func (x *LatLong) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatLong.ProtoReflect.Descriptor instead.
func (*LatLong) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *LatLong) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LatLong) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ChargePortLatchState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*ChargePortLatchState_SNA
	//	*ChargePortLatchState_Disengaged
	//	*ChargePortLatchState_Engaged
	//	*ChargePortLatchState_Blocking
	Type          isChargePortLatchState_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargePortLatchState) Reset() {
	*x = ChargePortLatchState{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargePortLatchState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargePortLatchState) ProtoMessage() {}

func (x *ChargePortLatchState) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargePortLatchState.ProtoReflect.Descriptor instead.
func (*ChargePortLatchState) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *ChargePortLatchState) GetType() isChargePortLatchState_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ChargePortLatchState) GetSNA() *Void {
	if x != nil {
		if x, ok := x.Type.(*ChargePortLatchState_SNA); ok {
			return x.SNA
		}
	}
	return nil
}

func (x *ChargePortLatchState) GetDisengaged() *Void {
	if x != nil {
		if x, ok := x.Type.(*ChargePortLatchState_Disengaged); ok {
			return x.Disengaged
		}
	}
	return nil
}

func (x *ChargePortLatchState) GetEngaged() *Void {
	if x != nil {
		if x, ok := x.Type.(*ChargePortLatchState_Engaged); ok {
			return x.Engaged
		}
	}
	return nil
}

func (x *ChargePortLatchState) GetBlocking() *Void {
	if x != nil {
		if x, ok := x.Type.(*ChargePortLatchState_Blocking); ok {
			return x.Blocking
		}
	}
	return nil
}

type isChargePortLatchState_Type interface {
	isChargePortLatchState_Type()
}

type ChargePortLatchState_SNA struct {
	SNA *Void `protobuf:"bytes,1,opt,name=SNA,proto3,oneof"`
}

type ChargePortLatchState_Disengaged struct {
	Disengaged *Void `protobuf:"bytes,2,opt,name=Disengaged,proto3,oneof"`
}

type ChargePortLatchState_Engaged struct {
	Engaged *Void `protobuf:"bytes,3,opt,name=Engaged,proto3,oneof"`
}

type ChargePortLatchState_Blocking struct {
	Blocking *Void `protobuf:"bytes,4,opt,name=Blocking,proto3,oneof"`
}

func (*ChargePortLatchState_SNA) isChargePortLatchState_Type() {}

func (*ChargePortLatchState_Disengaged) isChargePortLatchState_Type() {}

func (*ChargePortLatchState_Engaged) isChargePortLatchState_Type() {}

func (*ChargePortLatchState_Blocking) isChargePortLatchState_Type() {}

type PreconditioningTimes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Times:
	//
	//	*PreconditioningTimes_AllWeek
	//	*PreconditioningTimes_Weekdays
	Times         isPreconditioningTimes_Times `protobuf_oneof:"times"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreconditioningTimes) Reset() {
	*x = PreconditioningTimes{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreconditioningTimes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreconditioningTimes) ProtoMessage() {}

func (x *PreconditioningTimes) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreconditioningTimes.ProtoReflect.Descriptor instead.
func (*PreconditioningTimes) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *PreconditioningTimes) GetTimes() isPreconditioningTimes_Times {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *PreconditioningTimes) GetAllWeek() *Void {
	if x != nil {
		if x, ok := x.Times.(*PreconditioningTimes_AllWeek); ok {
			return x.AllWeek
		}
	}
	return nil
}

func (x *PreconditioningTimes) GetWeekdays() *Void {
	if x != nil {
		if x, ok := x.Times.(*PreconditioningTimes_Weekdays); ok {
			return x.Weekdays
		}
	}
	return nil
}

type isPreconditioningTimes_Times interface {
	isPreconditioningTimes_Times()
}

type PreconditioningTimes_AllWeek struct {
	AllWeek *Void `protobuf:"bytes,1,opt,name=all_week,json=allWeek,proto3,oneof"`
}

type PreconditioningTimes_Weekdays struct {
	Weekdays *Void `protobuf:"bytes,2,opt,name=weekdays,proto3,oneof"`
}

func (*PreconditioningTimes_AllWeek) isPreconditioningTimes_Times() {}

func (*PreconditioningTimes_Weekdays) isPreconditioningTimes_Times() {}

type OffPeakChargingTimes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Times:
	//
	//	*OffPeakChargingTimes_AllWeek
	//	*OffPeakChargingTimes_Weekdays
	Times         isOffPeakChargingTimes_Times `protobuf_oneof:"times"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OffPeakChargingTimes) Reset() {
	*x = OffPeakChargingTimes{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffPeakChargingTimes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffPeakChargingTimes) ProtoMessage() {}

func (x *OffPeakChargingTimes) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffPeakChargingTimes.ProtoReflect.Descriptor instead.
func (*OffPeakChargingTimes) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *OffPeakChargingTimes) GetTimes() isOffPeakChargingTimes_Times {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *OffPeakChargingTimes) GetAllWeek() *Void {
	if x != nil {
		if x, ok := x.Times.(*OffPeakChargingTimes_AllWeek); ok {
			return x.AllWeek
		}
	}
	return nil
}

func (x *OffPeakChargingTimes) GetWeekdays() *Void {
	if x != nil {
		if x, ok := x.Times.(*OffPeakChargingTimes_Weekdays); ok {
			return x.Weekdays
		}
	}
	return nil
}

type isOffPeakChargingTimes_Times interface {
	isOffPeakChargingTimes_Times()
}

type OffPeakChargingTimes_AllWeek struct {
	AllWeek *Void `protobuf:"bytes,1,opt,name=all_week,json=allWeek,proto3,oneof"`
}

type OffPeakChargingTimes_Weekdays struct {
	Weekdays *Void `protobuf:"bytes,2,opt,name=weekdays,proto3,oneof"`
}

func (*OffPeakChargingTimes_AllWeek) isOffPeakChargingTimes_Times() {}

func (*OffPeakChargingTimes_Weekdays) isOffPeakChargingTimes_Times() {}

type ChargeSchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // datetime in epoch time
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DaysOfWeek    int32                  `protobuf:"varint,3,opt,name=days_of_week,json=daysOfWeek,proto3" json:"days_of_week,omitempty"`
	StartEnabled  bool                   `protobuf:"varint,4,opt,name=start_enabled,json=startEnabled,proto3" json:"start_enabled,omitempty"`
	StartTime     int32                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 24h in minutes
	EndEnabled    bool                   `protobuf:"varint,6,opt,name=end_enabled,json=endEnabled,proto3" json:"end_enabled,omitempty"`
	EndTime       int32                  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"` // 24h in minutes
	OneTime       bool                   `protobuf:"varint,8,opt,name=one_time,json=oneTime,proto3" json:"one_time,omitempty"`
	Enabled       bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Latitude      float32                `protobuf:"fixed32,10,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,11,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargeSchedule) Reset() {
	*x = ChargeSchedule{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeSchedule) ProtoMessage() {}

func (x *ChargeSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeSchedule.ProtoReflect.Descriptor instead.
func (*ChargeSchedule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *ChargeSchedule) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChargeSchedule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChargeSchedule) GetDaysOfWeek() int32 {
	if x != nil {
		return x.DaysOfWeek
	}
	return 0
}

func (x *ChargeSchedule) GetStartEnabled() bool {
	if x != nil {
		return x.StartEnabled
	}
	return false
}

func (x *ChargeSchedule) GetStartTime() int32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ChargeSchedule) GetEndEnabled() bool {
	if x != nil {
		return x.EndEnabled
	}
	return false
}

func (x *ChargeSchedule) GetEndTime() int32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ChargeSchedule) GetOneTime() bool {
	if x != nil {
		return x.OneTime
	}
	return false
}

func (x *ChargeSchedule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ChargeSchedule) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ChargeSchedule) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type PreconditionSchedule struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // datetime in epoch time
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DaysOfWeek       int32                  `protobuf:"varint,3,opt,name=days_of_week,json=daysOfWeek,proto3" json:"days_of_week,omitempty"`
	PreconditionTime int32                  `protobuf:"varint,4,opt,name=precondition_time,json=preconditionTime,proto3" json:"precondition_time,omitempty"` // 24h in minutes
	OneTime          bool                   `protobuf:"varint,5,opt,name=one_time,json=oneTime,proto3" json:"one_time,omitempty"`
	Enabled          bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Latitude         float32                `protobuf:"fixed32,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float32                `protobuf:"fixed32,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PreconditionSchedule) Reset() {
	*x = PreconditionSchedule{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreconditionSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreconditionSchedule) ProtoMessage() {}

func (x *PreconditionSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreconditionSchedule.ProtoReflect.Descriptor instead.
func (*PreconditionSchedule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *PreconditionSchedule) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PreconditionSchedule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PreconditionSchedule) GetDaysOfWeek() int32 {
	if x != nil {
		return x.DaysOfWeek
	}
	return 0
}

func (x *PreconditionSchedule) GetPreconditionTime() int32 {
	if x != nil {
		return x.PreconditionTime
	}
	return 0
}

func (x *PreconditionSchedule) GetOneTime() bool {
	if x != nil {
		return x.OneTime
	}
	return false
}

func (x *PreconditionSchedule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PreconditionSchedule) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PreconditionSchedule) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\tCarServer\"\x06\n" +
	"\x04Void\"C\n" +
	"\aLatLong\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x02R\tlongitude\"\xd2\x01\n" +
	"\x14ChargePortLatchState\x12#\n" +
	"\x03SNA\x18\x01 \x01(\v2\x0f.CarServer.VoidH\x00R\x03SNA\x121\n" +
	"\n" +
	"Disengaged\x18\x02 \x01(\v2\x0f.CarServer.VoidH\x00R\n" +
	"Disengaged\x12+\n" +
	"\aEngaged\x18\x03 \x01(\v2\x0f.CarServer.VoidH\x00R\aEngaged\x12-\n" +
	"\bBlocking\x18\x04 \x01(\v2\x0f.CarServer.VoidH\x00R\bBlockingB\x06\n" +
	"\x04type\"|\n" +
	"\x14PreconditioningTimes\x12,\n" +
	"\ball_week\x18\x01 \x01(\v2\x0f.CarServer.VoidH\x00R\aallWeek\x12-\n" +
	"\bweekdays\x18\x02 \x01(\v2\x0f.CarServer.VoidH\x00R\bweekdaysB\a\n" +
	"\x05times\"|\n" +
	"\x14OffPeakChargingTimes\x12,\n" +
	"\ball_week\x18\x01 \x01(\v2\x0f.CarServer.VoidH\x00R\aallWeek\x12-\n" +
	"\bweekdays\x18\x02 \x01(\v2\x0f.CarServer.VoidH\x00R\bweekdaysB\a\n" +
	"\x05times\"\xc5\x02\n" +
	"\x0eChargeSchedule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\fdays_of_week\x18\x03 \x01(\x05R\n" +
	"daysOfWeek\x12#\n" +
	"\rstart_enabled\x18\x04 \x01(\bR\fstartEnabled\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x05R\tstartTime\x12\x1f\n" +
	"\vend_enabled\x18\x06 \x01(\bR\n" +
	"endEnabled\x12\x19\n" +
	"\bend_time\x18\a \x01(\x05R\aendTime\x12\x19\n" +
	"\bone_time\x18\b \x01(\bR\aoneTime\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\x12\x1a\n" +
	"\blatitude\x18\n" +
	" \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\v \x01(\x02R\tlongitude\"\xf8\x01\n" +
	"\x14PreconditionSchedule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\fdays_of_week\x18\x03 \x01(\x05R\n" +
	"daysOfWeek\x12+\n" +
	"\x11precondition_time\x18\x04 \x01(\x05R\x10preconditionTime\x12\x19\n" +
	"\bone_time\x18\x05 \x01(\bR\aoneTime\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x02R\tlongitude*\x16\n" +
	"\aInvalid\x12\v\n" +
	"\aINVALID\x10\x00*;\n" +
	"\x13MediaPlaybackStatus\x12\v\n" +
	"\aStopped\x10\x00\x12\v\n" +
	"\aPlaying\x10\x01\x12\n" +
	"\n" +
	"\x06Paused\x10\x02*k\n" +
	"\fStwHeatLevel\x12\x18\n" +
	"\x14StwHeatLevel_Unknown\x10\x00\x12\x14\n" +
	"\x10StwHeatLevel_Off\x10\x01\x12\x14\n" +
	"\x10StwHeatLevel_Low\x10\x02\x12\x15\n" +
	"\x11StwHeatLevel_High\x10\x03Bn\n" +
	"$com.tesla.generated.carserver.commonZFgithub.com/teslamotors/vehicle-command/pkg/protocol/protobuf/carserverb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_proto_goTypes = []any{
	(Invalid)(0),                 // 0: CarServer.Invalid
	(MediaPlaybackStatus)(0),     // 1: CarServer.MediaPlaybackStatus
	(StwHeatLevel)(0),            // 2: CarServer.StwHeatLevel
	(*Void)(nil),                 // 3: CarServer.Void
	(*LatLong)(nil),              // 4: CarServer.LatLong
	(*ChargePortLatchState)(nil), // 5: CarServer.ChargePortLatchState
	(*PreconditioningTimes)(nil), // 6: CarServer.PreconditioningTimes
	(*OffPeakChargingTimes)(nil), // 7: CarServer.OffPeakChargingTimes
	(*ChargeSchedule)(nil),       // 8: CarServer.ChargeSchedule
	(*PreconditionSchedule)(nil), // 9: CarServer.PreconditionSchedule
}
var file_common_proto_depIdxs = []int32{
	3, // 0: CarServer.ChargePortLatchState.SNA:type_name -> CarServer.Void
	3, // 1: CarServer.ChargePortLatchState.Disengaged:type_name -> CarServer.Void
	3, // 2: CarServer.ChargePortLatchState.Engaged:type_name -> CarServer.Void
	3, // 3: CarServer.ChargePortLatchState.Blocking:type_name -> CarServer.Void
	3, // 4: CarServer.PreconditioningTimes.all_week:type_name -> CarServer.Void
	3, // 5: CarServer.PreconditioningTimes.weekdays:type_name -> CarServer.Void
	3, // 6: CarServer.OffPeakChargingTimes.all_week:type_name -> CarServer.Void
	3, // 7: CarServer.OffPeakChargingTimes.weekdays:type_name -> CarServer.Void
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[2].OneofWrappers = []any{
		(*ChargePortLatchState_SNA)(nil),
		(*ChargePortLatchState_Disengaged)(nil),
		(*ChargePortLatchState_Engaged)(nil),
		(*ChargePortLatchState_Blocking)(nil),
	}
	file_common_proto_msgTypes[3].OneofWrappers = []any{
		(*PreconditioningTimes_AllWeek)(nil),
		(*PreconditioningTimes_Weekdays)(nil),
	}
	file_common_proto_msgTypes[4].OneofWrappers = []any{
		(*OffPeakChargingTimes_AllWeek)(nil),
		(*OffPeakChargingTimes_Weekdays)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
