// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.23.4
// source: signatures.proto

package signatures

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag int32

const (
	Tag_TAG_SIGNATURE_TYPE  Tag = 0
	Tag_TAG_DOMAIN          Tag = 1
	Tag_TAG_PERSONALIZATION Tag = 2
	Tag_TAG_EPOCH           Tag = 3
	Tag_TAG_EXPIRES_AT      Tag = 4
	Tag_TAG_COUNTER         Tag = 5
	Tag_TAG_CHALLENGE       Tag = 6
	Tag_TAG_FLAGS           Tag = 7
	Tag_TAG_REQUEST_HASH    Tag = 8
	Tag_TAG_FAULT           Tag = 9
	Tag_TAG_END             Tag = 255
)

// Enum value maps for Tag.
var (
	Tag_name = map[int32]string{
		0:   "TAG_SIGNATURE_TYPE",
		1:   "TAG_DOMAIN",
		2:   "TAG_PERSONALIZATION",
		3:   "TAG_EPOCH",
		4:   "TAG_EXPIRES_AT",
		5:   "TAG_COUNTER",
		6:   "TAG_CHALLENGE",
		7:   "TAG_FLAGS",
		8:   "TAG_REQUEST_HASH",
		9:   "TAG_FAULT",
		255: "TAG_END",
	}
	Tag_value = map[string]int32{
		"TAG_SIGNATURE_TYPE":  0,
		"TAG_DOMAIN":          1,
		"TAG_PERSONALIZATION": 2,
		"TAG_EPOCH":           3,
		"TAG_EXPIRES_AT":      4,
		"TAG_COUNTER":         5,
		"TAG_CHALLENGE":       6,
		"TAG_FLAGS":           7,
		"TAG_REQUEST_HASH":    8,
		"TAG_FAULT":           9,
		"TAG_END":             255,
	}
)

func (x Tag) Enum() *Tag {
	p := new(Tag)
	*p = x
	return p
}

func (x Tag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tag) Descriptor() protoreflect.EnumDescriptor {
	return file_signatures_proto_enumTypes[0].Descriptor()
}

func (Tag) Type() protoreflect.EnumType {
	return &file_signatures_proto_enumTypes[0]
}

func (x Tag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tag.Descriptor instead.
func (Tag) EnumDescriptor() ([]byte, []int) {
	return file_signatures_proto_rawDescGZIP(), []int{0}
}

type SignatureType int32

const (
	SignatureType_SIGNATURE_TYPE_AES_GCM              SignatureType = 0
	SignatureType_SIGNATURE_TYPE_AES_GCM_PERSONALIZED SignatureType = 5
	SignatureType_SIGNATURE_TYPE_HMAC                 SignatureType = 6
	SignatureType_SIGNATURE_TYPE_HMAC_PERSONALIZED    SignatureType = 8
	SignatureType_SIGNATURE_TYPE_AES_GCM_RESPONSE     SignatureType = 9
)

// Enum value maps for SignatureType.
var (
	SignatureType_name = map[int32]string{
		0: "SIGNATURE_TYPE_AES_GCM",
		5: "SIGNATURE_TYPE_AES_GCM_PERSONALIZED",
		6: "SIGNATURE_TYPE_HMAC",
		8: "SIGNATURE_TYPE_HMAC_PERSONALIZED",
		9: "SIGNATURE_TYPE_AES_GCM_RESPONSE",
	}
	SignatureType_value = map[string]int32{
		"SIGNATURE_TYPE_AES_GCM":              0,
		"SIGNATURE_TYPE_AES_GCM_PERSONALIZED": 5,
		"SIGNATURE_TYPE_HMAC":                 6,
		"SIGNATURE_TYPE_HMAC_PERSONALIZED":    8,
		"SIGNATURE_TYPE_AES_GCM_RESPONSE":     9,
	}
)

func (x SignatureType) Enum() *SignatureType {
	p := new(SignatureType)
	*p = x
	return p
}

func (x SignatureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignatureType) Descriptor() protoreflect.EnumDescriptor {
	return file_signatures_proto_enumTypes[1].Descriptor()
}

func (SignatureType) Type() protoreflect.EnumType {
	return &file_signatures_proto_enumTypes[1]
}

func (x SignatureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignatureType.Descriptor instead.
func (SignatureType) EnumDescriptor() ([]byte, []int) {
	return file_signatures_proto_rawDescGZIP(), []int{1}
}

type Session_Info_Status int32

const (
	Session_Info_Status_SESSION_INFO_STATUS_OK                   Session_Info_Status = 0
	Session_Info_Status_SESSION_INFO_STATUS_KEY_NOT_ON_WHITELIST Session_Info_Status = 1
)

// Enum value maps for Session_Info_Status.
var (
	Session_Info_Status_name = map[int32]string{
		0: "SESSION_INFO_STATUS_OK",
		1: "SESSION_INFO_STATUS_KEY_NOT_ON_WHITELIST",
	}
	Session_Info_Status_value = map[string]int32{
		"SESSION_INFO_STATUS_OK":                   0,
		"SESSION_INFO_STATUS_KEY_NOT_ON_WHITELIST": 1,
	}
)

func (x Session_Info_Status) Enum() *Session_Info_Status {
	p := new(Session_Info_Status)
	*p = x
	return p
}

func (x Session_Info_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Session_Info_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_signatures_proto_enumTypes[2].Descriptor()
}

func (Session_Info_Status) Type() protoreflect.EnumType {
	return &file_signatures_proto_enumTypes[2]
}

func (x Session_Info_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Session_Info_Status.Descriptor instead.
func (Session_Info_Status) EnumDescriptor() ([]byte, []int) {
	return file_signatures_proto_rawDescGZIP(), []int{2}
}

type KeyIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to IdentityType:
	//
	//	*KeyIdentity_PublicKey
	//	*KeyIdentity_Handle
	IdentityType  isKeyIdentity_IdentityType `protobuf_oneof:"identity_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyIdentity) Reset() {
	*x = KeyIdentity{}
	mi := &file_signatures_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyIdentity) ProtoMessage() {}

func (x *KeyIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_signatures_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyIdentity.ProtoReflect.Descriptor instead.
func (*KeyIdentity) Descriptor() ([]byte, []int) {
	return file_signatures_proto_rawDescGZIP(), []int{0}
}

func (x *KeyIdentity) GetIdentityType() isKeyIdentity_IdentityType {
	if x != nil {
		return x.IdentityType
	}
	return nil
}

func (x *KeyIdentity) GetPublicKey() []byte {
	if x != nil {
		if x, ok := x.IdentityType.(*KeyIdentity_PublicKey); ok {
			return x.PublicKey
		}
	}
	return nil
}

func (x *KeyIdentity) GetHandle() uint32 {
	if x != nil {
		if x, ok := x.IdentityType.(*KeyIdentity_Handle); ok {
			return x.Handle
		}
	}
	return 0
}

type isKeyIdentity_IdentityType interface {
	isKeyIdentity_IdentityType()
}

type KeyIdentity_PublicKey struct {
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3,oneof"`
}

type KeyIdentity_Handle struct {
	Handle uint32 `protobuf:"varint,3,opt,name=handle,proto3,oneof"`
}

func (*KeyIdentity_PublicKey) isKeyIdentity_IdentityType() {}

func (*KeyIdentity_Handle) isKeyIdentity_IdentityType() {}

type AES_GCM_Personalized_Signature_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         []byte                 `protobuf:"bytes,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Counter       uint32                 `protobuf:"varint,3,opt,name=counter,proto3" json:"counter,omitempty"`
	ExpiresAt     uint32                 `protobuf:"fixed32,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Tag           []byte                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AES_GCM_Personalized_Signature_Data) Reset() {
	*x = AES_GCM_Personalized_Signature_Data{}
	mi := &file_signatures_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AES_GCM_Personalized_Signature_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AES_GCM_Personalized_Signature_Data) ProtoMessage() {}

func (x *AES_GCM_Personalized_Signature_Data) ProtoReflect() protoreflect.Message {
	mi := &file_signatures_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AES_GCM_Personalized_Signature_Data.ProtoReflect.Descriptor instead.
func (*AES_GCM_Personalized_Signature_Data) Descriptor() ([]byte, []int) {
	return file_signatures_proto_rawDescGZIP(), []int{1}
}

func (x *AES_GCM_Personalized_Signature_Data) GetEpoch() []byte {
	if x != nil {
		return x.Epoch
	}
	return nil
}

func (x *AES_GCM_Personalized_Signature_Data) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *AES_GCM_Personalized_Signature_Data) GetCounter() uint32 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *AES_GCM_Personalized_Signature_Data) GetExpiresAt() uint32 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AES_GCM_Personalized_Signature_Data) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

type AES_GCM_Response_Signature_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Counter       uint32                 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	Tag           []byte                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AES_GCM_Response_Signature_Data) Reset() {
	*x = AES_GCM_Response_Signature_Data{}
	mi := &file_signatures_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AES_GCM_Response_Signature_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AES_GCM_Response_Signature_Data) ProtoMessage() {}

func (x *AES_GCM_Response_Signature_Data) ProtoReflect() protoreflect.Message {
	mi := &file_signatures_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AES_GCM_Response_Signature_Data.ProtoReflect.Descriptor instead.
func (*AES_GCM_Response_Signature_Data) Descriptor() ([]byte, []int) {
	return file_signatures_proto_rawDescGZIP(), []int{2}
}

func (x *AES_GCM_Response_Signature_Data) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *AES_GCM_Response_Signature_Data) GetCounter() uint32 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *AES_GCM_Response_Signature_Data) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

type HMAC_Signature_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           []byte                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HMAC_Signature_Data) Reset() {
	*x = HMAC_Signature_Data{}
	mi := &file_signatures_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HMAC_Signature_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HMAC_Signature_Data) ProtoMessage() {}

func (x *HMAC_Signature_Data) ProtoReflect() protoreflect.Message {
	mi := &file_signatures_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HMAC_Signature_Data.ProtoReflect.Descriptor instead.
func (*HMAC_Signature_Data) Descriptor() ([]byte, []int) {
	return file_signatures_proto_rawDescGZIP(), []int{3}
}

func (x *HMAC_Signature_Data) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

type HMAC_Personalized_Signature_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         []byte                 `protobuf:"bytes,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Counter       uint32                 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	ExpiresAt     uint32                 `protobuf:"fixed32,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Tag           []byte                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HMAC_Personalized_Signature_Data) Reset() {
	*x = HMAC_Personalized_Signature_Data{}
	mi := &file_signatures_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HMAC_Personalized_Signature_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HMAC_Personalized_Signature_Data) ProtoMessage() {}

func (x *HMAC_Personalized_Signature_Data) ProtoReflect() protoreflect.Message {
	mi := &file_signatures_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HMAC_Personalized_Signature_Data.ProtoReflect.Descriptor instead.
func (*HMAC_Personalized_Signature_Data) Descriptor() ([]byte, []int) {
	return file_signatures_proto_rawDescGZIP(), []int{4}
}

func (x *HMAC_Personalized_Signature_Data) GetEpoch() []byte {
	if x != nil {
		return x.Epoch
	}
	return nil
}

func (x *HMAC_Personalized_Signature_Data) GetCounter() uint32 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *HMAC_Personalized_Signature_Data) GetExpiresAt() uint32 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *HMAC_Personalized_Signature_Data) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

type SignatureData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SignerIdentity *KeyIdentity           `protobuf:"bytes,1,opt,name=signer_identity,json=signerIdentity,proto3" json:"signer_identity,omitempty"`
	// Types that are valid to be assigned to SigType:
	//
	//	*SignatureData_AES_GCM_PersonalizedData
	//	*SignatureData_SessionInfoTag
	//	*SignatureData_HMAC_PersonalizedData
	//	*SignatureData_AES_GCM_ResponseData
	SigType       isSignatureData_SigType `protobuf_oneof:"sig_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureData) Reset() {
	*x = SignatureData{}
	mi := &file_signatures_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureData) ProtoMessage() {}

func (x *SignatureData) ProtoReflect() protoreflect.Message {
	mi := &file_signatures_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureData.ProtoReflect.Descriptor instead.
func (*SignatureData) Descriptor() ([]byte, []int) {
	return file_signatures_proto_rawDescGZIP(), []int{5}
}

func (x *SignatureData) GetSignerIdentity() *KeyIdentity {
	if x != nil {
		return x.SignerIdentity
	}
	return nil
}

func (x *SignatureData) GetSigType() isSignatureData_SigType {
	if x != nil {
		return x.SigType
	}
	return nil
}

func (x *SignatureData) GetAES_GCM_PersonalizedData() *AES_GCM_Personalized_Signature_Data {
	if x != nil {
		if x, ok := x.SigType.(*SignatureData_AES_GCM_PersonalizedData); ok {
			return x.AES_GCM_PersonalizedData
		}
	}
	return nil
}

func (x *SignatureData) GetSessionInfoTag() *HMAC_Signature_Data {
	if x != nil {
		if x, ok := x.SigType.(*SignatureData_SessionInfoTag); ok {
			return x.SessionInfoTag
		}
	}
	return nil
}

func (x *SignatureData) GetHMAC_PersonalizedData() *HMAC_Personalized_Signature_Data {
	if x != nil {
		if x, ok := x.SigType.(*SignatureData_HMAC_PersonalizedData); ok {
			return x.HMAC_PersonalizedData
		}
	}
	return nil
}

func (x *SignatureData) GetAES_GCM_ResponseData() *AES_GCM_Response_Signature_Data {
	if x != nil {
		if x, ok := x.SigType.(*SignatureData_AES_GCM_ResponseData); ok {
			return x.AES_GCM_ResponseData
		}
	}
	return nil
}

type isSignatureData_SigType interface {
	isSignatureData_SigType()
}

type SignatureData_AES_GCM_PersonalizedData struct {
	AES_GCM_PersonalizedData *AES_GCM_Personalized_Signature_Data `protobuf:"bytes,5,opt,name=AES_GCM_Personalized_data,json=AESGCMPersonalizedData,proto3,oneof"`
}

type SignatureData_SessionInfoTag struct {
	SessionInfoTag *HMAC_Signature_Data `protobuf:"bytes,6,opt,name=session_info_tag,json=sessionInfoTag,proto3,oneof"`
}

type SignatureData_HMAC_PersonalizedData struct {
	HMAC_PersonalizedData *HMAC_Personalized_Signature_Data `protobuf:"bytes,8,opt,name=HMAC_Personalized_data,json=HMACPersonalizedData,proto3,oneof"`
}

type SignatureData_AES_GCM_ResponseData struct {
	AES_GCM_ResponseData *AES_GCM_Response_Signature_Data `protobuf:"bytes,9,opt,name=AES_GCM_Response_data,json=AESGCMResponseData,proto3,oneof"`
}

func (*SignatureData_AES_GCM_PersonalizedData) isSignatureData_SigType() {}

func (*SignatureData_SessionInfoTag) isSignatureData_SigType() {}

func (*SignatureData_HMAC_PersonalizedData) isSignatureData_SigType() {}

func (*SignatureData_AES_GCM_ResponseData) isSignatureData_SigType() {}

type GetSessionInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyIdentity   *KeyIdentity           `protobuf:"bytes,1,opt,name=key_identity,json=keyIdentity,proto3" json:"key_identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionInfoRequest) Reset() {
	*x = GetSessionInfoRequest{}
	mi := &file_signatures_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionInfoRequest) ProtoMessage() {}

func (x *GetSessionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signatures_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSessionInfoRequest) Descriptor() ([]byte, []int) {
	return file_signatures_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionInfoRequest) GetKeyIdentity() *KeyIdentity {
	if x != nil {
		return x.KeyIdentity
	}
	return nil
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counter       uint32                 `protobuf:"varint,1,opt,name=counter,proto3" json:"counter,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Epoch         []byte                 `protobuf:"bytes,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ClockTime     uint32                 `protobuf:"fixed32,4,opt,name=clock_time,json=clockTime,proto3" json:"clock_time,omitempty"`
	Status        Session_Info_Status    `protobuf:"varint,5,opt,name=status,proto3,enum=Signatures.Session_Info_Status" json:"status,omitempty"`
	Handle        uint32                 `protobuf:"varint,6,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_signatures_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_signatures_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_signatures_proto_rawDescGZIP(), []int{7}
}

func (x *SessionInfo) GetCounter() uint32 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *SessionInfo) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SessionInfo) GetEpoch() []byte {
	if x != nil {
		return x.Epoch
	}
	return nil
}

func (x *SessionInfo) GetClockTime() uint32 {
	if x != nil {
		return x.ClockTime
	}
	return 0
}

func (x *SessionInfo) GetStatus() Session_Info_Status {
	if x != nil {
		return x.Status
	}
	return Session_Info_Status_SESSION_INFO_STATUS_OK
}

func (x *SessionInfo) GetHandle() uint32 {
	if x != nil {
		return x.Handle
	}
	return 0
}

var File_signatures_proto protoreflect.FileDescriptor

const file_signatures_proto_rawDesc = "" +
	"\n" +
	"\x10signatures.proto\x12\n" +
	"Signatures\"_\n" +
	"\vKeyIdentity\x12\x1f\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fH\x00R\tpublicKey\x12\x18\n" +
	"\x06handle\x18\x03 \x01(\rH\x00R\x06handleB\x0f\n" +
	"\ridentity_typeJ\x04\b\x02\x10\x03\"\x9c\x01\n" +
	"#AES_GCM_Personalized_Signature_Data\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\fR\x05epoch\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x18\n" +
	"\acounter\x18\x03 \x01(\rR\acounter\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\aR\texpiresAt\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\fR\x03tag\"c\n" +
	"\x1fAES_GCM_Response_Signature_Data\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x18\n" +
	"\acounter\x18\x02 \x01(\rR\acounter\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\fR\x03tag\"'\n" +
	"\x13HMAC_Signature_Data\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\fR\x03tag\"\x83\x01\n" +
	" HMAC_Personalized_Signature_Data\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\fR\x05epoch\x12\x18\n" +
	"\acounter\x18\x02 \x01(\rR\acounter\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\aR\texpiresAt\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\fR\x03tag\"\xe6\x03\n" +
	"\rSignatureData\x12@\n" +
	"\x0fsigner_identity\x18\x01 \x01(\v2\x17.Signatures.KeyIdentityR\x0esignerIdentity\x12l\n" +
	"\x19AES_GCM_Personalized_data\x18\x05 \x01(\v2/.Signatures.AES_GCM_Personalized_Signature_DataH\x00R\x16AESGCMPersonalizedData\x12K\n" +
	"\x10session_info_tag\x18\x06 \x01(\v2\x1f.Signatures.HMAC_Signature_DataH\x00R\x0esessionInfoTag\x12d\n" +
	"\x16HMAC_Personalized_data\x18\b \x01(\v2,.Signatures.HMAC_Personalized_Signature_DataH\x00R\x14HMACPersonalizedData\x12`\n" +
	"\x15AES_GCM_Response_data\x18\t \x01(\v2+.Signatures.AES_GCM_Response_Signature_DataH\x00R\x12AESGCMResponseDataB\n" +
	"\n" +
	"\bsig_typeJ\x04\b\a\x10\b\"S\n" +
	"\x15GetSessionInfoRequest\x12:\n" +
	"\fkey_identity\x18\x01 \x01(\v2\x17.Signatures.KeyIdentityR\vkeyIdentity\"\xcb\x01\n" +
	"\vSessionInfo\x12\x18\n" +
	"\acounter\x18\x01 \x01(\rR\acounter\x12\x1c\n" +
	"\tpublicKey\x18\x02 \x01(\fR\tpublicKey\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\fR\x05epoch\x12\x1d\n" +
	"\n" +
	"clock_time\x18\x04 \x01(\aR\tclockTime\x127\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1f.Signatures.Session_Info_StatusR\x06status\x12\x16\n" +
	"\x06handle\x18\x06 \x01(\rR\x06handle*\xcf\x01\n" +
	"\x03Tag\x12\x16\n" +
	"\x12TAG_SIGNATURE_TYPE\x10\x00\x12\x0e\n" +
	"\n" +
	"TAG_DOMAIN\x10\x01\x12\x17\n" +
	"\x13TAG_PERSONALIZATION\x10\x02\x12\r\n" +
	"\tTAG_EPOCH\x10\x03\x12\x12\n" +
	"\x0eTAG_EXPIRES_AT\x10\x04\x12\x0f\n" +
	"\vTAG_COUNTER\x10\x05\x12\x11\n" +
	"\rTAG_CHALLENGE\x10\x06\x12\r\n" +
	"\tTAG_FLAGS\x10\a\x12\x14\n" +
	"\x10TAG_REQUEST_HASH\x10\b\x12\r\n" +
	"\tTAG_FAULT\x10\t\x12\f\n" +
	"\aTAG_END\x10\xff\x01*\xbe\x01\n" +
	"\rSignatureType\x12\x1a\n" +
	"\x16SIGNATURE_TYPE_AES_GCM\x10\x00\x12'\n" +
	"#SIGNATURE_TYPE_AES_GCM_PERSONALIZED\x10\x05\x12\x17\n" +
	"\x13SIGNATURE_TYPE_HMAC\x10\x06\x12$\n" +
	" SIGNATURE_TYPE_HMAC_PERSONALIZED\x10\b\x12#\n" +
	"\x1fSIGNATURE_TYPE_AES_GCM_RESPONSE\x10\t\"\x04\b\a\x10\a*_\n" +
	"\x13Session_Info_Status\x12\x1a\n" +
	"\x16SESSION_INFO_STATUS_OK\x10\x00\x12,\n" +
	"(SESSION_INFO_STATUS_KEY_NOT_ON_WHITELIST\x10\x01Bi\n" +
	"\x1ecom.tesla.generated.signaturesZGgithub.com/teslamotors/vehicle-command/pkg/protocol/protobuf/signaturesb\x06proto3"

var (
	file_signatures_proto_rawDescOnce sync.Once
	file_signatures_proto_rawDescData []byte
)

func file_signatures_proto_rawDescGZIP() []byte {
	file_signatures_proto_rawDescOnce.Do(func() {
		file_signatures_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signatures_proto_rawDesc), len(file_signatures_proto_rawDesc)))
	})
	return file_signatures_proto_rawDescData
}

var file_signatures_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_signatures_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_signatures_proto_goTypes = []any{
	(Tag)(0),                 // 0: Signatures.Tag
	(SignatureType)(0),       // 1: Signatures.SignatureType
	(Session_Info_Status)(0), // 2: Signatures.Session_Info_Status
	(*KeyIdentity)(nil),      // 3: Signatures.KeyIdentity
	(*AES_GCM_Personalized_Signature_Data)(nil), // 4: Signatures.AES_GCM_Personalized_Signature_Data
	(*AES_GCM_Response_Signature_Data)(nil),     // 5: Signatures.AES_GCM_Response_Signature_Data
	(*HMAC_Signature_Data)(nil),                 // 6: Signatures.HMAC_Signature_Data
	(*HMAC_Personalized_Signature_Data)(nil),    // 7: Signatures.HMAC_Personalized_Signature_Data
	(*SignatureData)(nil),                       // 8: Signatures.SignatureData
	(*GetSessionInfoRequest)(nil),               // 9: Signatures.GetSessionInfoRequest
	(*SessionInfo)(nil),                         // 10: Signatures.SessionInfo
}
var file_signatures_proto_depIdxs = []int32{
	3, // 0: Signatures.SignatureData.signer_identity:type_name -> Signatures.KeyIdentity
	4, // 1: Signatures.SignatureData.AES_GCM_Personalized_data:type_name -> Signatures.AES_GCM_Personalized_Signature_Data
	6, // 2: Signatures.SignatureData.session_info_tag:type_name -> Signatures.HMAC_Signature_Data
	7, // 3: Signatures.SignatureData.HMAC_Personalized_data:type_name -> Signatures.HMAC_Personalized_Signature_Data
	5, // 4: Signatures.SignatureData.AES_GCM_Response_data:type_name -> Signatures.AES_GCM_Response_Signature_Data
	3, // 5: Signatures.GetSessionInfoRequest.key_identity:type_name -> Signatures.KeyIdentity
	2, // 6: Signatures.SessionInfo.status:type_name -> Signatures.Session_Info_Status
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_signatures_proto_init() }
func file_signatures_proto_init() {
	if File_signatures_proto != nil {
		return
	}
	file_signatures_proto_msgTypes[0].OneofWrappers = []any{
		(*KeyIdentity_PublicKey)(nil),
		(*KeyIdentity_Handle)(nil),
	}
	file_signatures_proto_msgTypes[5].OneofWrappers = []any{
		(*SignatureData_AES_GCM_PersonalizedData)(nil),
		(*SignatureData_SessionInfoTag)(nil),
		(*SignatureData_HMAC_PersonalizedData)(nil),
		(*SignatureData_AES_GCM_ResponseData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signatures_proto_rawDesc), len(file_signatures_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_signatures_proto_goTypes,
		DependencyIndexes: file_signatures_proto_depIdxs,
		EnumInfos:         file_signatures_proto_enumTypes,
		MessageInfos:      file_signatures_proto_msgTypes,
	}.Build()
	File_signatures_proto = out.File
	file_signatures_proto_goTypes = nil
	file_signatures_proto_depIdxs = nil
}
