// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.23.4
// source: keys.proto

package keys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_NONE             Role = 0
	Role_ROLE_SERVICE          Role = 1
	Role_ROLE_OWNER            Role = 2
	Role_ROLE_DRIVER           Role = 3
	Role_ROLE_FM               Role = 4
	Role_ROLE_VEHICLE_MONITOR  Role = 5
	Role_ROLE_CHARGING_MANAGER Role = 6
	Role_ROLE_GUEST            Role = 8
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_NONE",
		1: "ROLE_SERVICE",
		2: "ROLE_OWNER",
		3: "ROLE_DRIVER",
		4: "ROLE_FM",
		5: "ROLE_VEHICLE_MONITOR",
		6: "ROLE_CHARGING_MANAGER",
		8: "ROLE_GUEST",
	}
	Role_value = map[string]int32{
		"ROLE_NONE":             0,
		"ROLE_SERVICE":          1,
		"ROLE_OWNER":            2,
		"ROLE_DRIVER":           3,
		"ROLE_FM":               4,
		"ROLE_VEHICLE_MONITOR":  5,
		"ROLE_CHARGING_MANAGER": 6,
		"ROLE_GUEST":            8,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_keys_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_keys_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_keys_proto_rawDescGZIP(), []int{0}
}

var File_keys_proto protoreflect.FileDescriptor

const file_keys_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"keys.proto\x12\x04Keys*\x9a\x01\n" +
	"\x04Role\x12\r\n" +
	"\tROLE_NONE\x10\x00\x12\x10\n" +
	"\fROLE_SERVICE\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_OWNER\x10\x02\x12\x0f\n" +
	"\vROLE_DRIVER\x10\x03\x12\v\n" +
	"\aROLE_FM\x10\x04\x12\x18\n" +
	"\x14ROLE_VEHICLE_MONITOR\x10\x05\x12\x19\n" +
	"\x15ROLE_CHARGING_MANAGER\x10\x06\x12\x0e\n" +
	"\n" +
	"ROLE_GUEST\x10\bB]\n" +
	"\x18com.tesla.generated.keysZAgithub.com/teslamotors/vehicle-command/pkg/protocol/protobuf/keysb\x06proto3"

var (
	file_keys_proto_rawDescOnce sync.Once
	file_keys_proto_rawDescData []byte
)

func file_keys_proto_rawDescGZIP() []byte {
	file_keys_proto_rawDescOnce.Do(func() {
		file_keys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keys_proto_rawDesc), len(file_keys_proto_rawDesc)))
	})
	return file_keys_proto_rawDescData
}

var file_keys_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keys_proto_goTypes = []any{
	(Role)(0), // 0: Keys.Role
}
var file_keys_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keys_proto_init() }
func file_keys_proto_init() {
	if File_keys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keys_proto_rawDesc), len(file_keys_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keys_proto_goTypes,
		DependencyIndexes: file_keys_proto_depIdxs,
		EnumInfos:         file_keys_proto_enumTypes,
	}.Build()
	File_keys_proto = out.File
	file_keys_proto_goTypes = nil
	file_keys_proto_depIdxs = nil
}
