// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.23.4
// source: universal_message.proto

package universalmessage

import (
	signatures "github.com/teslamotors/vehicle-command/pkg/protocol/protobuf/signatures"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Domain int32

const (
	Domain_DOMAIN_BROADCAST        Domain = 0
	Domain_DOMAIN_VEHICLE_SECURITY Domain = 2
	Domain_DOMAIN_INFOTAINMENT     Domain = 3
)

// Enum value maps for Domain.
var (
	Domain_name = map[int32]string{
		0: "DOMAIN_BROADCAST",
		2: "DOMAIN_VEHICLE_SECURITY",
		3: "DOMAIN_INFOTAINMENT",
	}
	Domain_value = map[string]int32{
		"DOMAIN_BROADCAST":        0,
		"DOMAIN_VEHICLE_SECURITY": 2,
		"DOMAIN_INFOTAINMENT":     3,
	}
)

func (x Domain) Enum() *Domain {
	p := new(Domain)
	*p = x
	return p
}

func (x Domain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Domain) Descriptor() protoreflect.EnumDescriptor {
	return file_universal_message_proto_enumTypes[0].Descriptor()
}

func (Domain) Type() protoreflect.EnumType {
	return &file_universal_message_proto_enumTypes[0]
}

func (x Domain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Domain.Descriptor instead.
func (Domain) EnumDescriptor() ([]byte, []int) {
	return file_universal_message_proto_rawDescGZIP(), []int{0}
}

type OperationStatus_E int32

const (
	OperationStatus_E_OPERATIONSTATUS_OK    OperationStatus_E = 0
	OperationStatus_E_OPERATIONSTATUS_WAIT  OperationStatus_E = 1
	OperationStatus_E_OPERATIONSTATUS_ERROR OperationStatus_E = 2
)

// Enum value maps for OperationStatus_E.
var (
	OperationStatus_E_name = map[int32]string{
		0: "OPERATIONSTATUS_OK",
		1: "OPERATIONSTATUS_WAIT",
		2: "OPERATIONSTATUS_ERROR",
	}
	OperationStatus_E_value = map[string]int32{
		"OPERATIONSTATUS_OK":    0,
		"OPERATIONSTATUS_WAIT":  1,
		"OPERATIONSTATUS_ERROR": 2,
	}
)

func (x OperationStatus_E) Enum() *OperationStatus_E {
	p := new(OperationStatus_E)
	*p = x
	return p
}

func (x OperationStatus_E) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus_E) Descriptor() protoreflect.EnumDescriptor {
	return file_universal_message_proto_enumTypes[1].Descriptor()
}

func (OperationStatus_E) Type() protoreflect.EnumType {
	return &file_universal_message_proto_enumTypes[1]
}

func (x OperationStatus_E) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus_E.Descriptor instead.
func (OperationStatus_E) EnumDescriptor() ([]byte, []int) {
	return file_universal_message_proto_rawDescGZIP(), []int{1}
}

type MessageFault_E int32

const (
	MessageFault_E_MESSAGEFAULT_ERROR_NONE                                 MessageFault_E = 0  // Request succeeded.
	MessageFault_E_MESSAGEFAULT_ERROR_BUSY                                 MessageFault_E = 1  // Required vehicle subsystem is busy. Try again.
	MessageFault_E_MESSAGEFAULT_ERROR_TIMEOUT                              MessageFault_E = 2  // Vehicle subsystem did not respond. Try again.
	MessageFault_E_MESSAGEFAULT_ERROR_UNKNOWN_KEY_ID                       MessageFault_E = 3  // Vehicle did not recognize the key used to authorize command. Make sure your key is paired with the vehicle.
	MessageFault_E_MESSAGEFAULT_ERROR_INACTIVE_KEY                         MessageFault_E = 4  // Key used to authorize command has been disabled.
	MessageFault_E_MESSAGEFAULT_ERROR_INVALID_SIGNATURE                    MessageFault_E = 5  // Command signature/MAC is incorrect. Use included session info to update session and try again.
	MessageFault_E_MESSAGEFAULT_ERROR_INVALID_TOKEN_OR_COUNTER             MessageFault_E = 6  // Command anti-replay counter has been used before. Use included session info to update session and try again.
	MessageFault_E_MESSAGEFAULT_ERROR_INSUFFICIENT_PRIVILEGES              MessageFault_E = 7  // User is not authorized to execute command. This can be because of the role or because of vehicle state.
	MessageFault_E_MESSAGEFAULT_ERROR_INVALID_DOMAINS                      MessageFault_E = 8  // Command was malformed or addressed to an unrecognized vehicle system. May indicate client error or older vehicle firmware.
	MessageFault_E_MESSAGEFAULT_ERROR_INVALID_COMMAND                      MessageFault_E = 9  // Unrecognized command. May indicate client error or unsupported vehicle firmware.
	MessageFault_E_MESSAGEFAULT_ERROR_DECODING                             MessageFault_E = 10 // Could not parse command. Indicates client error.
	MessageFault_E_MESSAGEFAULT_ERROR_INTERNAL                             MessageFault_E = 11 // Internal vehicle error. Try again. Most commonly encountered when the vehicle has not finished booting.
	MessageFault_E_MESSAGEFAULT_ERROR_WRONG_PERSONALIZATION                MessageFault_E = 12 // Command sent to wrong VIN.
	MessageFault_E_MESSAGEFAULT_ERROR_BAD_PARAMETER                        MessageFault_E = 13 // Command was malformed or used a deprecated parameter.
	MessageFault_E_MESSAGEFAULT_ERROR_KEYCHAIN_IS_FULL                     MessageFault_E = 14 // Vehicle's keychain is full. You must delete a key before you can add another.
	MessageFault_E_MESSAGEFAULT_ERROR_INCORRECT_EPOCH                      MessageFault_E = 15 // Session ID mismatch. Use included session info to update session and try again.
	MessageFault_E_MESSAGEFAULT_ERROR_IV_INCORRECT_LENGTH                  MessageFault_E = 16 // Initialization Value length is incorrect (AES-GCM must use 12-byte IVs). Indicates a client programming error.
	MessageFault_E_MESSAGEFAULT_ERROR_TIME_EXPIRED                         MessageFault_E = 17 // Command expired. Use included session info to determine if clocks have desynchronized and try again.
	MessageFault_E_MESSAGEFAULT_ERROR_NOT_PROVISIONED_WITH_IDENTITY        MessageFault_E = 18 // Vehicle has not been provisioned with a VIN and may require service.
	MessageFault_E_MESSAGEFAULT_ERROR_COULD_NOT_HASH_METADATA              MessageFault_E = 19 // Internal vehicle error.
	MessageFault_E_MESSAGEFAULT_ERROR_TIME_TO_LIVE_TOO_LONG                MessageFault_E = 20 // Vehicle rejected command because its expiration time was too far in the future. This is a security precaution.
	MessageFault_E_MESSAGEFAULT_ERROR_REMOTE_ACCESS_DISABLED               MessageFault_E = 21 // The vehicle owner has disabled Mobile access.
	MessageFault_E_MESSAGEFAULT_ERROR_REMOTE_SERVICE_ACCESS_DISABLED       MessageFault_E = 22 // The command was authorized with a Service key, but the vehicle has not been configured to permit remote service commands.
	MessageFault_E_MESSAGEFAULT_ERROR_COMMAND_REQUIRES_ACCOUNT_CREDENTIALS MessageFault_E = 23 // The command requires proof of Tesla account credentials but was not sent over a channel that provides this proof. Resend the command using Fleet API.
	MessageFault_E_MESSAGEFAULT_ERROR_REQUEST_MTU_EXCEEDED                 MessageFault_E = 24 // Client sent a request with a field that exceeds MTU
	MessageFault_E_MESSAGEFAULT_ERROR_RESPONSE_MTU_EXCEEDED                MessageFault_E = 25 // Client's request was received, but response size exceeded MTU
	MessageFault_E_MESSAGEFAULT_ERROR_REPEATED_COUNTER                     MessageFault_E = 26
	MessageFault_E_MESSAGEFAULT_ERROR_INVALID_KEY_HANDLE                   MessageFault_E = 27
	MessageFault_E_MESSAGEFAULT_ERROR_REQUIRES_RESPONSE_ENCRYPTION         MessageFault_E = 28
)

// Enum value maps for MessageFault_E.
var (
	MessageFault_E_name = map[int32]string{
		0:  "MESSAGEFAULT_ERROR_NONE",
		1:  "MESSAGEFAULT_ERROR_BUSY",
		2:  "MESSAGEFAULT_ERROR_TIMEOUT",
		3:  "MESSAGEFAULT_ERROR_UNKNOWN_KEY_ID",
		4:  "MESSAGEFAULT_ERROR_INACTIVE_KEY",
		5:  "MESSAGEFAULT_ERROR_INVALID_SIGNATURE",
		6:  "MESSAGEFAULT_ERROR_INVALID_TOKEN_OR_COUNTER",
		7:  "MESSAGEFAULT_ERROR_INSUFFICIENT_PRIVILEGES",
		8:  "MESSAGEFAULT_ERROR_INVALID_DOMAINS",
		9:  "MESSAGEFAULT_ERROR_INVALID_COMMAND",
		10: "MESSAGEFAULT_ERROR_DECODING",
		11: "MESSAGEFAULT_ERROR_INTERNAL",
		12: "MESSAGEFAULT_ERROR_WRONG_PERSONALIZATION",
		13: "MESSAGEFAULT_ERROR_BAD_PARAMETER",
		14: "MESSAGEFAULT_ERROR_KEYCHAIN_IS_FULL",
		15: "MESSAGEFAULT_ERROR_INCORRECT_EPOCH",
		16: "MESSAGEFAULT_ERROR_IV_INCORRECT_LENGTH",
		17: "MESSAGEFAULT_ERROR_TIME_EXPIRED",
		18: "MESSAGEFAULT_ERROR_NOT_PROVISIONED_WITH_IDENTITY",
		19: "MESSAGEFAULT_ERROR_COULD_NOT_HASH_METADATA",
		20: "MESSAGEFAULT_ERROR_TIME_TO_LIVE_TOO_LONG",
		21: "MESSAGEFAULT_ERROR_REMOTE_ACCESS_DISABLED",
		22: "MESSAGEFAULT_ERROR_REMOTE_SERVICE_ACCESS_DISABLED",
		23: "MESSAGEFAULT_ERROR_COMMAND_REQUIRES_ACCOUNT_CREDENTIALS",
		24: "MESSAGEFAULT_ERROR_REQUEST_MTU_EXCEEDED",
		25: "MESSAGEFAULT_ERROR_RESPONSE_MTU_EXCEEDED",
		26: "MESSAGEFAULT_ERROR_REPEATED_COUNTER",
		27: "MESSAGEFAULT_ERROR_INVALID_KEY_HANDLE",
		28: "MESSAGEFAULT_ERROR_REQUIRES_RESPONSE_ENCRYPTION",
	}
	MessageFault_E_value = map[string]int32{
		"MESSAGEFAULT_ERROR_NONE":                                 0,
		"MESSAGEFAULT_ERROR_BUSY":                                 1,
		"MESSAGEFAULT_ERROR_TIMEOUT":                              2,
		"MESSAGEFAULT_ERROR_UNKNOWN_KEY_ID":                       3,
		"MESSAGEFAULT_ERROR_INACTIVE_KEY":                         4,
		"MESSAGEFAULT_ERROR_INVALID_SIGNATURE":                    5,
		"MESSAGEFAULT_ERROR_INVALID_TOKEN_OR_COUNTER":             6,
		"MESSAGEFAULT_ERROR_INSUFFICIENT_PRIVILEGES":              7,
		"MESSAGEFAULT_ERROR_INVALID_DOMAINS":                      8,
		"MESSAGEFAULT_ERROR_INVALID_COMMAND":                      9,
		"MESSAGEFAULT_ERROR_DECODING":                             10,
		"MESSAGEFAULT_ERROR_INTERNAL":                             11,
		"MESSAGEFAULT_ERROR_WRONG_PERSONALIZATION":                12,
		"MESSAGEFAULT_ERROR_BAD_PARAMETER":                        13,
		"MESSAGEFAULT_ERROR_KEYCHAIN_IS_FULL":                     14,
		"MESSAGEFAULT_ERROR_INCORRECT_EPOCH":                      15,
		"MESSAGEFAULT_ERROR_IV_INCORRECT_LENGTH":                  16,
		"MESSAGEFAULT_ERROR_TIME_EXPIRED":                         17,
		"MESSAGEFAULT_ERROR_NOT_PROVISIONED_WITH_IDENTITY":        18,
		"MESSAGEFAULT_ERROR_COULD_NOT_HASH_METADATA":              19,
		"MESSAGEFAULT_ERROR_TIME_TO_LIVE_TOO_LONG":                20,
		"MESSAGEFAULT_ERROR_REMOTE_ACCESS_DISABLED":               21,
		"MESSAGEFAULT_ERROR_REMOTE_SERVICE_ACCESS_DISABLED":       22,
		"MESSAGEFAULT_ERROR_COMMAND_REQUIRES_ACCOUNT_CREDENTIALS": 23,
		"MESSAGEFAULT_ERROR_REQUEST_MTU_EXCEEDED":                 24,
		"MESSAGEFAULT_ERROR_RESPONSE_MTU_EXCEEDED":                25,
		"MESSAGEFAULT_ERROR_REPEATED_COUNTER":                     26,
		"MESSAGEFAULT_ERROR_INVALID_KEY_HANDLE":                   27,
		"MESSAGEFAULT_ERROR_REQUIRES_RESPONSE_ENCRYPTION":         28,
	}
)

func (x MessageFault_E) Enum() *MessageFault_E {
	p := new(MessageFault_E)
	*p = x
	return p
}

func (x MessageFault_E) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageFault_E) Descriptor() protoreflect.EnumDescriptor {
	return file_universal_message_proto_enumTypes[2].Descriptor()
}

func (MessageFault_E) Type() protoreflect.EnumType {
	return &file_universal_message_proto_enumTypes[2]
}

func (x MessageFault_E) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageFault_E.Descriptor instead.
func (MessageFault_E) EnumDescriptor() ([]byte, []int) {
	return file_universal_message_proto_rawDescGZIP(), []int{2}
}

type Flags int32

const (
	Flags_FLAG_USER_COMMAND     Flags = 0
	Flags_FLAG_ENCRYPT_RESPONSE Flags = 1
)

// Enum value maps for Flags.
var (
	Flags_name = map[int32]string{
		0: "FLAG_USER_COMMAND",
		1: "FLAG_ENCRYPT_RESPONSE",
	}
	Flags_value = map[string]int32{
		"FLAG_USER_COMMAND":     0,
		"FLAG_ENCRYPT_RESPONSE": 1,
	}
)

func (x Flags) Enum() *Flags {
	p := new(Flags)
	*p = x
	return p
}

func (x Flags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Flags) Descriptor() protoreflect.EnumDescriptor {
	return file_universal_message_proto_enumTypes[3].Descriptor()
}

func (Flags) Type() protoreflect.EnumType {
	return &file_universal_message_proto_enumTypes[3]
}

func (x Flags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Flags.Descriptor instead.
func (Flags) EnumDescriptor() ([]byte, []int) {
	return file_universal_message_proto_rawDescGZIP(), []int{3}
}

type Destination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to SubDestination:
	//
	//	*Destination_Domain
	//	*Destination_RoutingAddress
	SubDestination isDestination_SubDestination `protobuf_oneof:"sub_destination"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Destination) Reset() {
	*x = Destination{}
	mi := &file_universal_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination) ProtoMessage() {}

func (x *Destination) ProtoReflect() protoreflect.Message {
	mi := &file_universal_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination.ProtoReflect.Descriptor instead.
func (*Destination) Descriptor() ([]byte, []int) {
	return file_universal_message_proto_rawDescGZIP(), []int{0}
}

func (x *Destination) GetSubDestination() isDestination_SubDestination {
	if x != nil {
		return x.SubDestination
	}
	return nil
}

func (x *Destination) GetDomain() Domain {
	if x != nil {
		if x, ok := x.SubDestination.(*Destination_Domain); ok {
			return x.Domain
		}
	}
	return Domain_DOMAIN_BROADCAST
}

func (x *Destination) GetRoutingAddress() []byte {
	if x != nil {
		if x, ok := x.SubDestination.(*Destination_RoutingAddress); ok {
			return x.RoutingAddress
		}
	}
	return nil
}

type isDestination_SubDestination interface {
	isDestination_SubDestination()
}

type Destination_Domain struct {
	Domain Domain `protobuf:"varint,1,opt,name=domain,proto3,enum=UniversalMessage.Domain,oneof"`
}

type Destination_RoutingAddress struct {
	RoutingAddress []byte `protobuf:"bytes,2,opt,name=routing_address,json=routingAddress,proto3,oneof"`
}

func (*Destination_Domain) isDestination_SubDestination() {}

func (*Destination_RoutingAddress) isDestination_SubDestination() {}

type MessageStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OperationStatus    OperationStatus_E      `protobuf:"varint,1,opt,name=operation_status,json=operationStatus,proto3,enum=UniversalMessage.OperationStatus_E" json:"operation_status,omitempty"`
	SignedMessageFault MessageFault_E         `protobuf:"varint,2,opt,name=signed_message_fault,json=signedMessageFault,proto3,enum=UniversalMessage.MessageFault_E" json:"signed_message_fault,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MessageStatus) Reset() {
	*x = MessageStatus{}
	mi := &file_universal_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStatus) ProtoMessage() {}

func (x *MessageStatus) ProtoReflect() protoreflect.Message {
	mi := &file_universal_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStatus.ProtoReflect.Descriptor instead.
func (*MessageStatus) Descriptor() ([]byte, []int) {
	return file_universal_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageStatus) GetOperationStatus() OperationStatus_E {
	if x != nil {
		return x.OperationStatus
	}
	return OperationStatus_E_OPERATIONSTATUS_OK
}

func (x *MessageStatus) GetSignedMessageFault() MessageFault_E {
	if x != nil {
		return x.SignedMessageFault
	}
	return MessageFault_E_MESSAGEFAULT_ERROR_NONE
}

type SessionInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Challenge     []byte                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfoRequest) Reset() {
	*x = SessionInfoRequest{}
	mi := &file_universal_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfoRequest) ProtoMessage() {}

func (x *SessionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_universal_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfoRequest.ProtoReflect.Descriptor instead.
func (*SessionInfoRequest) Descriptor() ([]byte, []int) {
	return file_universal_message_proto_rawDescGZIP(), []int{2}
}

func (x *SessionInfoRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SessionInfoRequest) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type RoutableMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ToDestination   *Destination           `protobuf:"bytes,6,opt,name=to_destination,json=toDestination,proto3" json:"to_destination,omitempty"`
	FromDestination *Destination           `protobuf:"bytes,7,opt,name=from_destination,json=fromDestination,proto3" json:"from_destination,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RoutableMessage_ProtobufMessageAsBytes
	//	*RoutableMessage_SessionInfoRequest
	//	*RoutableMessage_SessionInfo
	Payload isRoutableMessage_Payload `protobuf_oneof:"payload"`
	// Types that are valid to be assigned to SubSigData:
	//
	//	*RoutableMessage_SignatureData
	SubSigData          isRoutableMessage_SubSigData `protobuf_oneof:"sub_sigData"`
	SignedMessageStatus *MessageStatus               `protobuf:"bytes,12,opt,name=signedMessageStatus,proto3" json:"signedMessageStatus,omitempty"`
	RequestUuid         []byte                       `protobuf:"bytes,50,opt,name=request_uuid,json=requestUuid,proto3" json:"request_uuid,omitempty"`
	Uuid                []byte                       `protobuf:"bytes,51,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Flags               uint32                       `protobuf:"varint,52,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RoutableMessage) Reset() {
	*x = RoutableMessage{}
	mi := &file_universal_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutableMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutableMessage) ProtoMessage() {}

func (x *RoutableMessage) ProtoReflect() protoreflect.Message {
	mi := &file_universal_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutableMessage.ProtoReflect.Descriptor instead.
func (*RoutableMessage) Descriptor() ([]byte, []int) {
	return file_universal_message_proto_rawDescGZIP(), []int{3}
}

func (x *RoutableMessage) GetToDestination() *Destination {
	if x != nil {
		return x.ToDestination
	}
	return nil
}

func (x *RoutableMessage) GetFromDestination() *Destination {
	if x != nil {
		return x.FromDestination
	}
	return nil
}

func (x *RoutableMessage) GetPayload() isRoutableMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RoutableMessage) GetProtobufMessageAsBytes() []byte {
	if x != nil {
		if x, ok := x.Payload.(*RoutableMessage_ProtobufMessageAsBytes); ok {
			return x.ProtobufMessageAsBytes
		}
	}
	return nil
}

func (x *RoutableMessage) GetSessionInfoRequest() *SessionInfoRequest {
	if x != nil {
		if x, ok := x.Payload.(*RoutableMessage_SessionInfoRequest); ok {
			return x.SessionInfoRequest
		}
	}
	return nil
}

func (x *RoutableMessage) GetSessionInfo() []byte {
	if x != nil {
		if x, ok := x.Payload.(*RoutableMessage_SessionInfo); ok {
			return x.SessionInfo
		}
	}
	return nil
}

func (x *RoutableMessage) GetSubSigData() isRoutableMessage_SubSigData {
	if x != nil {
		return x.SubSigData
	}
	return nil
}

func (x *RoutableMessage) GetSignatureData() *signatures.SignatureData {
	if x != nil {
		if x, ok := x.SubSigData.(*RoutableMessage_SignatureData); ok {
			return x.SignatureData
		}
	}
	return nil
}

func (x *RoutableMessage) GetSignedMessageStatus() *MessageStatus {
	if x != nil {
		return x.SignedMessageStatus
	}
	return nil
}

func (x *RoutableMessage) GetRequestUuid() []byte {
	if x != nil {
		return x.RequestUuid
	}
	return nil
}

func (x *RoutableMessage) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *RoutableMessage) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type isRoutableMessage_Payload interface {
	isRoutableMessage_Payload()
}

type RoutableMessage_ProtobufMessageAsBytes struct {
	ProtobufMessageAsBytes []byte `protobuf:"bytes,10,opt,name=protobuf_message_as_bytes,json=protobufMessageAsBytes,proto3,oneof"`
}

type RoutableMessage_SessionInfoRequest struct {
	SessionInfoRequest *SessionInfoRequest `protobuf:"bytes,14,opt,name=session_info_request,json=sessionInfoRequest,proto3,oneof"`
}

type RoutableMessage_SessionInfo struct {
	SessionInfo []byte `protobuf:"bytes,15,opt,name=session_info,json=sessionInfo,proto3,oneof"`
}

func (*RoutableMessage_ProtobufMessageAsBytes) isRoutableMessage_Payload() {}

func (*RoutableMessage_SessionInfoRequest) isRoutableMessage_Payload() {}

func (*RoutableMessage_SessionInfo) isRoutableMessage_Payload() {}

type isRoutableMessage_SubSigData interface {
	isRoutableMessage_SubSigData()
}

type RoutableMessage_SignatureData struct {
	SignatureData *signatures.SignatureData `protobuf:"bytes,13,opt,name=signature_data,json=signatureData,proto3,oneof"`
}

func (*RoutableMessage_SignatureData) isRoutableMessage_SubSigData() {}

var File_universal_message_proto protoreflect.FileDescriptor

const file_universal_message_proto_rawDesc = "" +
	"\n" +
	"\x17universal_message.proto\x12\x10UniversalMessage\x1a\x10signatures.proto\"\x7f\n" +
	"\vDestination\x122\n" +
	"\x06domain\x18\x01 \x01(\x0e2\x18.UniversalMessage.DomainH\x00R\x06domain\x12)\n" +
	"\x0frouting_address\x18\x02 \x01(\fH\x00R\x0eroutingAddressB\x11\n" +
	"\x0fsub_destination\"\xb3\x01\n" +
	"\rMessageStatus\x12N\n" +
	"\x10operation_status\x18\x01 \x01(\x0e2#.UniversalMessage.OperationStatus_ER\x0foperationStatus\x12R\n" +
	"\x14signed_message_fault\x18\x02 \x01(\x0e2 .UniversalMessage.MessageFault_ER\x12signedMessageFault\"Q\n" +
	"\x12SessionInfoRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\fR\tchallenge\"\xed\x04\n" +
	"\x0fRoutableMessage\x12D\n" +
	"\x0eto_destination\x18\x06 \x01(\v2\x1d.UniversalMessage.DestinationR\rtoDestination\x12H\n" +
	"\x10from_destination\x18\a \x01(\v2\x1d.UniversalMessage.DestinationR\x0ffromDestination\x12;\n" +
	"\x19protobuf_message_as_bytes\x18\n" +
	" \x01(\fH\x00R\x16protobufMessageAsBytes\x12X\n" +
	"\x14session_info_request\x18\x0e \x01(\v2$.UniversalMessage.SessionInfoRequestH\x00R\x12sessionInfoRequest\x12#\n" +
	"\fsession_info\x18\x0f \x01(\fH\x00R\vsessionInfo\x12B\n" +
	"\x0esignature_data\x18\r \x01(\v2\x19.Signatures.SignatureDataH\x01R\rsignatureData\x12Q\n" +
	"\x13signedMessageStatus\x18\f \x01(\v2\x1f.UniversalMessage.MessageStatusR\x13signedMessageStatus\x12!\n" +
	"\frequest_uuid\x182 \x01(\fR\vrequestUuid\x12\x12\n" +
	"\x04uuid\x183 \x01(\fR\x04uuid\x12\x14\n" +
	"\x05flags\x184 \x01(\rR\x05flagsB\t\n" +
	"\apayloadB\r\n" +
	"\vsub_sigDataJ\x04\b\x01\x10\x06J\x04\b\x10\x10)J\x04\b\v\x10\f*T\n" +
	"\x06Domain\x12\x14\n" +
	"\x10DOMAIN_BROADCAST\x10\x00\x12\x1b\n" +
	"\x17DOMAIN_VEHICLE_SECURITY\x10\x02\x12\x17\n" +
	"\x13DOMAIN_INFOTAINMENT\x10\x03*`\n" +
	"\x11OperationStatus_E\x12\x16\n" +
	"\x12OPERATIONSTATUS_OK\x10\x00\x12\x18\n" +
	"\x14OPERATIONSTATUS_WAIT\x10\x01\x12\x19\n" +
	"\x15OPERATIONSTATUS_ERROR\x10\x02*\xe4\t\n" +
	"\x0eMessageFault_E\x12\x1b\n" +
	"\x17MESSAGEFAULT_ERROR_NONE\x10\x00\x12\x1b\n" +
	"\x17MESSAGEFAULT_ERROR_BUSY\x10\x01\x12\x1e\n" +
	"\x1aMESSAGEFAULT_ERROR_TIMEOUT\x10\x02\x12%\n" +
	"!MESSAGEFAULT_ERROR_UNKNOWN_KEY_ID\x10\x03\x12#\n" +
	"\x1fMESSAGEFAULT_ERROR_INACTIVE_KEY\x10\x04\x12(\n" +
	"$MESSAGEFAULT_ERROR_INVALID_SIGNATURE\x10\x05\x12/\n" +
	"+MESSAGEFAULT_ERROR_INVALID_TOKEN_OR_COUNTER\x10\x06\x12.\n" +
	"*MESSAGEFAULT_ERROR_INSUFFICIENT_PRIVILEGES\x10\a\x12&\n" +
	"\"MESSAGEFAULT_ERROR_INVALID_DOMAINS\x10\b\x12&\n" +
	"\"MESSAGEFAULT_ERROR_INVALID_COMMAND\x10\t\x12\x1f\n" +
	"\x1bMESSAGEFAULT_ERROR_DECODING\x10\n" +
	"\x12\x1f\n" +
	"\x1bMESSAGEFAULT_ERROR_INTERNAL\x10\v\x12,\n" +
	"(MESSAGEFAULT_ERROR_WRONG_PERSONALIZATION\x10\f\x12$\n" +
	" MESSAGEFAULT_ERROR_BAD_PARAMETER\x10\r\x12'\n" +
	"#MESSAGEFAULT_ERROR_KEYCHAIN_IS_FULL\x10\x0e\x12&\n" +
	"\"MESSAGEFAULT_ERROR_INCORRECT_EPOCH\x10\x0f\x12*\n" +
	"&MESSAGEFAULT_ERROR_IV_INCORRECT_LENGTH\x10\x10\x12#\n" +
	"\x1fMESSAGEFAULT_ERROR_TIME_EXPIRED\x10\x11\x124\n" +
	"0MESSAGEFAULT_ERROR_NOT_PROVISIONED_WITH_IDENTITY\x10\x12\x12.\n" +
	"*MESSAGEFAULT_ERROR_COULD_NOT_HASH_METADATA\x10\x13\x12,\n" +
	"(MESSAGEFAULT_ERROR_TIME_TO_LIVE_TOO_LONG\x10\x14\x12-\n" +
	")MESSAGEFAULT_ERROR_REMOTE_ACCESS_DISABLED\x10\x15\x125\n" +
	"1MESSAGEFAULT_ERROR_REMOTE_SERVICE_ACCESS_DISABLED\x10\x16\x12;\n" +
	"7MESSAGEFAULT_ERROR_COMMAND_REQUIRES_ACCOUNT_CREDENTIALS\x10\x17\x12+\n" +
	"'MESSAGEFAULT_ERROR_REQUEST_MTU_EXCEEDED\x10\x18\x12,\n" +
	"(MESSAGEFAULT_ERROR_RESPONSE_MTU_EXCEEDED\x10\x19\x12'\n" +
	"#MESSAGEFAULT_ERROR_REPEATED_COUNTER\x10\x1a\x12)\n" +
	"%MESSAGEFAULT_ERROR_INVALID_KEY_HANDLE\x10\x1b\x123\n" +
	"/MESSAGEFAULT_ERROR_REQUIRES_RESPONSE_ENCRYPTION\x10\x1c*9\n" +
	"\x05Flags\x12\x15\n" +
	"\x11FLAG_USER_COMMAND\x10\x00\x12\x19\n" +
	"\x15FLAG_ENCRYPT_RESPONSE\x10\x01Bu\n" +
	"$com.tesla.generated.universalmessageZMgithub.com/teslamotors/vehicle-command/pkg/protocol/protobuf/universalmessageb\x06proto3"

var (
	file_universal_message_proto_rawDescOnce sync.Once
	file_universal_message_proto_rawDescData []byte
)

func file_universal_message_proto_rawDescGZIP() []byte {
	file_universal_message_proto_rawDescOnce.Do(func() {
		file_universal_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_universal_message_proto_rawDesc), len(file_universal_message_proto_rawDesc)))
	})
	return file_universal_message_proto_rawDescData
}

var file_universal_message_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_universal_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_universal_message_proto_goTypes = []any{
	(Domain)(0),                      // 0: UniversalMessage.Domain
	(OperationStatus_E)(0),           // 1: UniversalMessage.OperationStatus_E
	(MessageFault_E)(0),              // 2: UniversalMessage.MessageFault_E
	(Flags)(0),                       // 3: UniversalMessage.Flags
	(*Destination)(nil),              // 4: UniversalMessage.Destination
	(*MessageStatus)(nil),            // 5: UniversalMessage.MessageStatus
	(*SessionInfoRequest)(nil),       // 6: UniversalMessage.SessionInfoRequest
	(*RoutableMessage)(nil),          // 7: UniversalMessage.RoutableMessage
	(*signatures.SignatureData)(nil), // 8: Signatures.SignatureData
}
var file_universal_message_proto_depIdxs = []int32{
	0, // 0: UniversalMessage.Destination.domain:type_name -> UniversalMessage.Domain
	1, // 1: UniversalMessage.MessageStatus.operation_status:type_name -> UniversalMessage.OperationStatus_E
	2, // 2: UniversalMessage.MessageStatus.signed_message_fault:type_name -> UniversalMessage.MessageFault_E
	4, // 3: UniversalMessage.RoutableMessage.to_destination:type_name -> UniversalMessage.Destination
	4, // 4: UniversalMessage.RoutableMessage.from_destination:type_name -> UniversalMessage.Destination
	6, // 5: UniversalMessage.RoutableMessage.session_info_request:type_name -> UniversalMessage.SessionInfoRequest
	8, // 6: UniversalMessage.RoutableMessage.signature_data:type_name -> Signatures.SignatureData
	5, // 7: UniversalMessage.RoutableMessage.signedMessageStatus:type_name -> UniversalMessage.MessageStatus
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_universal_message_proto_init() }
func file_universal_message_proto_init() {
	if File_universal_message_proto != nil {
		return
	}
	file_universal_message_proto_msgTypes[0].OneofWrappers = []any{
		(*Destination_Domain)(nil),
		(*Destination_RoutingAddress)(nil),
	}
	file_universal_message_proto_msgTypes[3].OneofWrappers = []any{
		(*RoutableMessage_ProtobufMessageAsBytes)(nil),
		(*RoutableMessage_SessionInfoRequest)(nil),
		(*RoutableMessage_SessionInfo)(nil),
		(*RoutableMessage_SignatureData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_universal_message_proto_rawDesc), len(file_universal_message_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_universal_message_proto_goTypes,
		DependencyIndexes: file_universal_message_proto_depIdxs,
		EnumInfos:         file_universal_message_proto_enumTypes,
		MessageInfos:      file_universal_message_proto_msgTypes,
	}.Build()
	File_universal_message_proto = out.File
	file_universal_message_proto_goTypes = nil
	file_universal_message_proto_depIdxs = nil
}
