// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.23.4
// source: errors.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenericError_E int32

const (
	GenericError_E_GENERICERROR_NONE                       GenericError_E = 0
	GenericError_E_GENERICERROR_UNKNOWN                    GenericError_E = 1
	GenericError_E_GENERICERROR_CLOSURES_OPEN              GenericError_E = 2
	GenericError_E_GENERICERROR_ALREADY_ON                 GenericError_E = 3
	GenericError_E_GENERICERROR_DISABLED_FOR_USER_COMMAND  GenericError_E = 4
	GenericError_E_GENERICERROR_VEHICLE_NOT_IN_PARK        GenericError_E = 5
	GenericError_E_GENERICERROR_UNAUTHORIZED               GenericError_E = 6
	GenericError_E_GENERICERROR_NOT_ALLOWED_OVER_TRANSPORT GenericError_E = 7
)

// Enum value maps for GenericError_E.
var (
	GenericError_E_name = map[int32]string{
		0: "GENERICERROR_NONE",
		1: "GENERICERROR_UNKNOWN",
		2: "GENERICERROR_CLOSURES_OPEN",
		3: "GENERICERROR_ALREADY_ON",
		4: "GENERICERROR_DISABLED_FOR_USER_COMMAND",
		5: "GENERICERROR_VEHICLE_NOT_IN_PARK",
		6: "GENERICERROR_UNAUTHORIZED",
		7: "GENERICERROR_NOT_ALLOWED_OVER_TRANSPORT",
	}
	GenericError_E_value = map[string]int32{
		"GENERICERROR_NONE":                       0,
		"GENERICERROR_UNKNOWN":                    1,
		"GENERICERROR_CLOSURES_OPEN":              2,
		"GENERICERROR_ALREADY_ON":                 3,
		"GENERICERROR_DISABLED_FOR_USER_COMMAND":  4,
		"GENERICERROR_VEHICLE_NOT_IN_PARK":        5,
		"GENERICERROR_UNAUTHORIZED":               6,
		"GENERICERROR_NOT_ALLOWED_OVER_TRANSPORT": 7,
	}
)

func (x GenericError_E) Enum() *GenericError_E {
	p := new(GenericError_E)
	*p = x
	return p
}

func (x GenericError_E) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenericError_E) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_proto_enumTypes[0].Descriptor()
}

func (GenericError_E) Type() protoreflect.EnumType {
	return &file_errors_proto_enumTypes[0]
}

func (x GenericError_E) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenericError_E.Descriptor instead.
func (GenericError_E) EnumDescriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

type NominalError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenericError  GenericError_E         `protobuf:"varint,1,opt,name=genericError,proto3,enum=Errors.GenericError_E" json:"genericError,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NominalError) Reset() {
	*x = NominalError{}
	mi := &file_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NominalError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NominalError) ProtoMessage() {}

func (x *NominalError) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NominalError.ProtoReflect.Descriptor instead.
func (*NominalError) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

func (x *NominalError) GetGenericError() GenericError_E {
	if x != nil {
		return x.GenericError
	}
	return GenericError_E_GENERICERROR_NONE
}

var File_errors_proto protoreflect.FileDescriptor

const file_errors_proto_rawDesc = "" +
	"\n" +
	"\ferrors.proto\x12\x06Errors\"J\n" +
	"\fNominalError\x12:\n" +
	"\fgenericError\x18\x01 \x01(\x0e2\x16.Errors.GenericError_ER\fgenericError*\x9c\x02\n" +
	"\x0eGenericError_E\x12\x15\n" +
	"\x11GENERICERROR_NONE\x10\x00\x12\x18\n" +
	"\x14GENERICERROR_UNKNOWN\x10\x01\x12\x1e\n" +
	"\x1aGENERICERROR_CLOSURES_OPEN\x10\x02\x12\x1b\n" +
	"\x17GENERICERROR_ALREADY_ON\x10\x03\x12*\n" +
	"&GENERICERROR_DISABLED_FOR_USER_COMMAND\x10\x04\x12$\n" +
	" GENERICERROR_VEHICLE_NOT_IN_PARK\x10\x05\x12\x1d\n" +
	"\x19GENERICERROR_UNAUTHORIZED\x10\x06\x12+\n" +
	"'GENERICERROR_NOT_ALLOWED_OVER_TRANSPORT\x10\aBa\n" +
	"\x1acom.tesla.generated.errorsZCgithub.com/teslamotors/vehicle-command/pkg/protocol/protobuf/errorsb\x06proto3"

var (
	file_errors_proto_rawDescOnce sync.Once
	file_errors_proto_rawDescData []byte
)

func file_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)))
	})
	return file_errors_proto_rawDescData
}

var file_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_errors_proto_goTypes = []any{
	(GenericError_E)(0),  // 0: Errors.GenericError_E
	(*NominalError)(nil), // 1: Errors.NominalError
}
var file_errors_proto_depIdxs = []int32{
	0, // 0: Errors.NominalError.genericError:type_name -> Errors.GenericError_E
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_errors_proto_init() }
func file_errors_proto_init() {
	if File_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_depIdxs,
		EnumInfos:         file_errors_proto_enumTypes,
		MessageInfos:      file_errors_proto_msgTypes,
	}.Build()
	File_errors_proto = out.File
	file_errors_proto_goTypes = nil
	file_errors_proto_depIdxs = nil
}
