// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.23.4
// source: managed_charging.proto

package managedcharging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The reasons why the site controller may recommend no charge.
// The site controller will only return the highest priority reason to the vehicle.
type ChargeOnSolarNoChargeReason int32

const (
	ChargeOnSolarNoChargeReason_CHARGE_ON_SOLAR_NO_CHARGE_REASON_INVALID ChargeOnSolarNoChargeReason = 0
	// The Powerwall is being prioritized over the vehicle to charge.
	ChargeOnSolarNoChargeReason_CHARGE_ON_SOLAR_NO_CHARGE_REASON_POWERWALL_CHARGE_PRIORITY ChargeOnSolarNoChargeReason = 1
	// There is not enough solar for the vehicle to charge effectively.
	ChargeOnSolarNoChargeReason_CHARGE_ON_SOLAR_NO_CHARGE_REASON_INSUFFICIENT_SOLAR ChargeOnSolarNoChargeReason = 2
	// The site controller is prioritizing export to the grid. This can
	// happen when the site controller is in autonomous mode and it is
	// most economical to export excess solar to the grid, or during a
	// virtual power plant event.
	ChargeOnSolarNoChargeReason_CHARGE_ON_SOLAR_NO_CHARGE_REASON_GRID_EXPORT_PRIORITY ChargeOnSolarNoChargeReason = 3
	// Another vehicle is charging on solar at this location and has priority.
	ChargeOnSolarNoChargeReason_CHARGE_ON_SOLAR_NO_CHARGE_REASON_ALTERNATE_VEHICLE_CHARGE_PRIORITY ChargeOnSolarNoChargeReason = 4
)

// Enum value maps for ChargeOnSolarNoChargeReason.
var (
	ChargeOnSolarNoChargeReason_name = map[int32]string{
		0: "CHARGE_ON_SOLAR_NO_CHARGE_REASON_INVALID",
		1: "CHARGE_ON_SOLAR_NO_CHARGE_REASON_POWERWALL_CHARGE_PRIORITY",
		2: "CHARGE_ON_SOLAR_NO_CHARGE_REASON_INSUFFICIENT_SOLAR",
		3: "CHARGE_ON_SOLAR_NO_CHARGE_REASON_GRID_EXPORT_PRIORITY",
		4: "CHARGE_ON_SOLAR_NO_CHARGE_REASON_ALTERNATE_VEHICLE_CHARGE_PRIORITY",
	}
	ChargeOnSolarNoChargeReason_value = map[string]int32{
		"CHARGE_ON_SOLAR_NO_CHARGE_REASON_INVALID":                           0,
		"CHARGE_ON_SOLAR_NO_CHARGE_REASON_POWERWALL_CHARGE_PRIORITY":         1,
		"CHARGE_ON_SOLAR_NO_CHARGE_REASON_INSUFFICIENT_SOLAR":                2,
		"CHARGE_ON_SOLAR_NO_CHARGE_REASON_GRID_EXPORT_PRIORITY":              3,
		"CHARGE_ON_SOLAR_NO_CHARGE_REASON_ALTERNATE_VEHICLE_CHARGE_PRIORITY": 4,
	}
)

func (x ChargeOnSolarNoChargeReason) Enum() *ChargeOnSolarNoChargeReason {
	p := new(ChargeOnSolarNoChargeReason)
	*p = x
	return p
}

func (x ChargeOnSolarNoChargeReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChargeOnSolarNoChargeReason) Descriptor() protoreflect.EnumDescriptor {
	return file_managed_charging_proto_enumTypes[0].Descriptor()
}

func (ChargeOnSolarNoChargeReason) Type() protoreflect.EnumType {
	return &file_managed_charging_proto_enumTypes[0]
}

func (x ChargeOnSolarNoChargeReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChargeOnSolarNoChargeReason.Descriptor instead.
func (ChargeOnSolarNoChargeReason) EnumDescriptor() ([]byte, []int) {
	return file_managed_charging_proto_rawDescGZIP(), []int{0}
}

var File_managed_charging_proto protoreflect.FileDescriptor

const file_managed_charging_proto_rawDesc = "" +
	"\n" +
	"\x16managed_charging.proto\x12\x0fManagedCharging*\xc7\x02\n" +
	"\x1bChargeOnSolarNoChargeReason\x12,\n" +
	"(CHARGE_ON_SOLAR_NO_CHARGE_REASON_INVALID\x10\x00\x12>\n" +
	":CHARGE_ON_SOLAR_NO_CHARGE_REASON_POWERWALL_CHARGE_PRIORITY\x10\x01\x127\n" +
	"3CHARGE_ON_SOLAR_NO_CHARGE_REASON_INSUFFICIENT_SOLAR\x10\x02\x129\n" +
	"5CHARGE_ON_SOLAR_NO_CHARGE_REASON_GRID_EXPORT_PRIORITY\x10\x03\x12F\n" +
	"BCHARGE_ON_SOLAR_NO_CHARGE_REASON_ALTERNATE_VEHICLE_CHARGE_PRIORITY\x10\x04BNZLgithub.com/teslamotors/vehicle-command/pkg/protocol/protobuf/managedchargingb\x06proto3"

var (
	file_managed_charging_proto_rawDescOnce sync.Once
	file_managed_charging_proto_rawDescData []byte
)

func file_managed_charging_proto_rawDescGZIP() []byte {
	file_managed_charging_proto_rawDescOnce.Do(func() {
		file_managed_charging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_managed_charging_proto_rawDesc), len(file_managed_charging_proto_rawDesc)))
	})
	return file_managed_charging_proto_rawDescData
}

var file_managed_charging_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_managed_charging_proto_goTypes = []any{
	(ChargeOnSolarNoChargeReason)(0), // 0: ManagedCharging.ChargeOnSolarNoChargeReason
}
var file_managed_charging_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_managed_charging_proto_init() }
func file_managed_charging_proto_init() {
	if File_managed_charging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_managed_charging_proto_rawDesc), len(file_managed_charging_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_managed_charging_proto_goTypes,
		DependencyIndexes: file_managed_charging_proto_depIdxs,
		EnumInfos:         file_managed_charging_proto_enumTypes,
	}.Build()
	File_managed_charging_proto = out.File
	file_managed_charging_proto_goTypes = nil
	file_managed_charging_proto_depIdxs = nil
}
